CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    name   text UNIQUE NOT NULL,
    password_hash text NOT NULL
);

CREATE TABLE IF NOT EXISTS signs
(
    hash   text NOT NULL,
    user_id bigint REFERENCES users(id),
    PRIMARY KEY (hash, user_id)
);